env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - './tsconfig.json'
    - './tsconfig.eslint.json'
plugins:
  - 'import'
  - '@typescript-eslint'
  - 'prettier'
  - 'tailwindcss'

ignorePatterns: ["*.min.js"]
rules:
  "@typescript-eslint/no-non-null-assertion":
    - off
  "@typescript-eslint/no-this-alias":
    - off
  "@typescript-eslint/no-explicit-any":
    - off
  "@typescript-eslint/ban-ts-comment":
    - off
  no-useless-escape:
    - off
  no-async-promise-executor:
    - off
  no-case-declarations:
    - off
  indent:
    - error
    - tab
  linebreak-style:
    - off
  quotes:
    - error
    - single
  semi:
    - error
    - always
  strict:
    - error
    - global
  no-duplicate-imports:
    - error
  no-self-compare:
    - error
  no-template-curly-in-string:
    - warn
  no-unmodified-loop-condition:
    - warn
  no-unreachable-loop:
    - warn
  no-unused-private-class-members:
    - error
  no-use-before-define:
    - off
  require-atomic-updates:
    - off
  block-scoped-var:
    - error
  complexity:
    - off
    - 25
  consistent-return:
    - off
  consistent-this:
    - off
    - that
  arrow-body-style:
    - off
    - as-needed
  curly:
    - off
  dot-notation:
    - error
  eqeqeq:
    - off
  func-names:
    - off
    - as-needed
  func-style:
    - off
    - expression
  guard-for-in:
    - off
  init-declarations:
    - off
    - always
  max-depth:
    - off
    - 3
  max-nested-callbacks:
    - off
    - 2
  new-cap:
    - off
    - properties: false # because of ComfyJS
  no-alert:
    - off
  no-array-constructor:
    - off
  no-bitwise:
    - off
  no-confusing-arrow:
    - error
  no-continue:
    - off
  no-div-regex:
    - error
  no-else-return:
    - warn
    - allowElseIf: false
  no-empty-function:
    - error
  no-eval:
    - off
  no-extend-native:
    - off
  no-extra-bind:
    - error
  no-floating-decimal:
    - error
  no-implicit-globals:
    - error
  no-implied-eval:
    - error
  no-inline-comments:
    - off
  no-invalid-this:
    - off
  no-iterator:
    - error
  no-labels:
    - error
  no-lone-blocks:
    - error
  no-lonely-if:
    - error
  no-loop-func:
    - error
  #no-magic-numbers:
  #  - warn
  #  - ignore:
  #    - 0
  #    - 1
  #    - 69
  #    - 404
  #    - 500
  #    ignoreDefaultValues: true
  #    ignoreArrayIndexes: true
  #    enforceConst: true
  no-mixed-operators:
    - off
  no-multi-assign:
    - off
  no-multi-str:
    - error
  no-negated-condition:
    - error
  no-nested-ternary:
    - off
  no-new:
    - error
  no-new-func:
    - off
  no-new-object:
    - error
  no-new-wrappers:
    - error
  no-octal-escape:
    - error
  no-param-reassign:
    - off
  no-plusplus:
    - off
  no-proto:
    - error
  no-return-assign:
    - off
  no-script-url:
    - error
  no-sequences:
    - error
  no-shadow:
    - off
  no-throw-literal:
    - error
  no-undefined:
    - off
  no-unneeded-ternary:
    - error
  no-undef-init:
    - error
  no-unused-expressions:
    - off
  no-useless-call:
    - error
  no-useless-computed-key:
    - error
  no-useless-concat:
    - error
  no-useless-constructor:
    - error
  no-useless-rename:
    - error
  no-useless-return:
    - error
  no-var:
    - error
  no-void:
    - error
  no-warning-comments:
    - off
  object-shorthand:
    - off
    - consistent-as-needed
  one-var:
    - error
    - never
  operator-assignment:
    - error
  prefer-arrow-callback:
    - error
  prefer-const:
    - error
  prefer-destructuring:
    - off
  prefer-exponentiation-operator:
    - error
  prefer-named-capture-group:
    - off
  prefer-numeric-literals:
    - error
  prefer-object-spread:
    - error
  prefer-promise-reject-errors:
    - error
  prefer-regex-literals:
    - error
  prefer-rest-params:
    - off
  prefer-spread:
    - error
  prefer-template:
    - warn
  radix:
    - error
  require-await:
    - error
  require-unicode-regexp:
    - error
  spaced-comment:
    - error
    - always
  symbol-description:
    - error
  yoda:
    - error
    - never
    - exceptRange: true
  array-bracket-newline:
    - error
    - multiline: true
  array-bracket-spacing:
    - error
    - never
  array-element-newline:
    - error
    - consistent
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: true
  arrow-spacing:
    - error
    - before: true
      after: true
  block-spacing:
    - error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  comma-dangle:
    - error
    - objects: always-multiline
      arrays: always-multiline
  comma-spacing:
    - error
  comma-style:
    - error
  computed-property-spacing:
    - error
  dot-location:
    - error
    - property
  eol-last:
    - error
  func-call-spacing:
    - error
  function-call-argument-newline:
    - error
    - consistent
  function-paren-newline:
    - error
    - consistent
  yield-star-spacing:
    - error
    - before: true
      after: false
  generator-star-spacing:
    - error
    - before: true
      after: false
  jsx-quotes:
    - error
  key-spacing:
    - error
  keyword-spacing:
    - error
    - before: true
      after: true
  lines-around-comment:
    - error
  lines-between-class-members:
  - error
  - always
  - exceptAfterSingleLine: true
  max-len:
    - warn
    - code: 150
      ignoreTemplateLiterals: true
      ignoreStrings: true
      ignoreComments: true
  max-statements-per-line:
    - off
  multiline-ternary:
    - error
    - never
  new-parens:
    - error
  newline-per-chained-call:
    - error
  no-extra-parens:
    - error
    - functions
  no-multiple-empty-lines:
    - error
  no-tabs:
    - off
  no-trailing-spaces:
    - error
  no-whitespace-before-property:
    - error
  object-curly-newline:
    - error
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  operator-linebreak:
    - error
    - before
  padded-blocks:
    - off
    - never
  rest-spread-spacing:
    - error
    - never
  semi-spacing:
    - error
  semi-style:
    - error
  space-before-blocks:
    - error
  space-before-function-paren:
    - off
  space-in-parens:
    - error
  space-infix-ops:
    - error
  space-unary-ops:
    - error
  switch-colon-spacing:
    - error
  template-curly-spacing:
    - error
  template-tag-spacing:
    - error
  unicode-bom:
    - error
  wrap-iife:
    - error
    - inside
  wrap-regex:
    - off
  no-multi-spaces:
    - error
    - exceptions:
        CallExpression: true
        AssignmentExpression: true
  no-console:
    - off
