name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:
  workflow_run:
    workflows:
      - Create Release
    types:
      - completed

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: rm -rf node_modules package-lock.json && npm install

      - name: Build package
        run: npm run build

      - name: Get version
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Publish package
        run: |
          if [[ "$VERSION" == *-* ]]; then
            npm publish --provenance --access public --tag beta
          else
            npm publish --provenance --access public
          fi
